Obligatorio Web/Controllers/GruposController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Dominio;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Obligatorio_Web.Controllers
{
    public class GruposController : Controller
    {
        Sistema s = Sistema.Instancia();

        // ActionResult que envia a la vista la lista de partidos 
        public IActionResult Index()
        {
            if (HttpContext.Session.GetInt32("Id") != null)
            {
                return View(s.GetPartidos());
            }
            return RedirectToAction("Index", "Home");
        }

        // Metodo get para cerrar partido de grupos
        [HttpGet]
        public IActionResult Close(int partidoId)
        {
            if (HttpContext.Session.GetString("Tipo") == "Operador")
            {
                FaseDeGrupos partidoBuscado = s.GetGrupos(partidoId);
                return View(partidoBuscado);
            }
            return RedirectToAction("Index", "Home");
        }

        // Metodo post para cerrar partido de grupos
        [HttpPost]
        public IActionResult Close(bool chequeado, int partidoId)
        {
            FaseDeGrupos partidoBuscado = s.GetGrupos(partidoId);

            if (chequeado)
            {
                s.FinalizarPartido(partidoBuscado);
                ViewBag.Msg = "Partido cerrado correctamente!";
            }
            else
            {
                ViewBag.Msg = "Debe confirmar el cierre del partido.";
            }
            return View(partidoBuscado);
        }
    }
}

Obligatorio Web/Controllers/PartidoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Dominio;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Obligatorio_Web.Controllers
{
    public class PartidoController : Controller
    {
        Sistema s = Sistema.Instancia();

        // IActionResult que envia a la vista la lista de partidos, asi como un metodo que nos indica si hay partidos finalizados
        public IActionResult Index()
        {
            if (HttpContext.Session.GetInt32("Id") != null)
            {
                ViewBag.Contador = s.PartidosFinalizados();
                return View(s.GetPartidos());
            }
            return RedirectToAction("Index", "Home");
        }

        //IActionResult (get) que envia a la vista del buscador de partidos
        [HttpGet]
        public IActionResult Buscar()
        {
            if (HttpContext.Session.GetString("Tipo") == "Operador")
            {
                return View();
            }
                return RedirectToAction("Index", "Home");
        }

        //IActionResult (post) que devuelve a la vista la lista de partidos finalizados entre dos fechas
        [HttpPost]
        public IActionResult Buscar(DateTime fecha1, DateTime fecha2)
        {
            List<Partido> listaFiltrada = s.GetPartidos(fecha1, fecha2);
            
            return View(listaFiltrada);
        }
    }
}

Obligatorio Web/Controllers/ReseniaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Dominio;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Obligatorio_Web.Controllers
{
    public class ReseniaController : Controller
    {
        Sistema s = Sistema.Instancia();

        // IactionResult que envia a la vista las reseñas de un determinado periodista
        // Verifica que sea periodista, y también si la lista de reseñas esta vacia o no
        public IActionResult Index()
        {
            int? idR = HttpContext.Session.GetInt32("Id");
            Usuario usuarioR = s.GetUsuario(idR);
            if (usuarioR != null)
            {
                if (HttpContext.Session.GetString("Tipo") == "Periodista")
                {
                    ViewBag.User = usuarioR;
                    string rol = HttpContext.Session.GetString("Tipo");
                    ViewBag.ListaVacia = s.ListaVaciaPeriodista((Periodista)usuarioR);
                    if (rol == "Periodista")
                    {
                        return View(s.GetResenias());
                    }
                }
            }
            return RedirectToAction("Index", "Home");
        }

        // IActionResult (get) que envia a la vista para que el peridoista realice una reseña
        [HttpGet]
        public IActionResult Create(int partidoId)
        {
            string rol = HttpContext.Session.GetString("Tipo");
            if (rol == "Periodista")
            {
                Partido partidoRes = s.GetPartido(partidoId);
                ViewBag.ElPartido = partidoRes;
                return View();
            }
                return RedirectToAction("Index", "Home");
        }

        // IActionResult (post) que obtiene los datos de la reseña, la da de alta en el sistema y envia mensaje a la vista
        [HttpPost]
        public IActionResult Create(int partidoId, string unTitulo, string unContenido)
        {
              Partido partidoR = s.GetPartido(partidoId);
              ViewBag.ElPartido = partidoR;
              int? idR = HttpContext.Session.GetInt32("Id");
              Usuario usuarioR = s.GetUsuario(idR);

              Resenia res = new Resenia();

              res.UnPartido = partidoR;
              res.UnPeriodista = usuarioR as Periodista;
              res.Fecha = DateTime.Now;
              res.Titulo = unTitulo;
              res.Contenido = unContenido;

              try
              {
                  s.AltaResenia(res);
                  ViewBag.Msg = "Datos guardados correctamente";
              }
              catch (Exception ex)
              {
                  ViewBag.Msg = ex.Message;
              }

              return View();
        }

        // IActionResult que envia a la vista los detalles de una reseña determinada
        public IActionResult Details(int id)
        {
            string rol = HttpContext.Session.GetString("Tipo");
            if (rol == "Periodista")
            {
                Resenia reseniaR = s.GetResenia(id);
                return View(reseniaR);
            }
                return RedirectToAction("Index", "Home");
        }

        // IActionResult (get) que envía a la vista del buscador de reseñas de partidos con tarjeta roja de un periodista 
        public IActionResult Estadisticas()
        {
            if (HttpContext.Session.GetString("Tipo") == "Operador")
            {
                return View();
            }
            return RedirectToAction("Index", "Home");
        }

        // IActionResult (post) que obtiene el email del periodista y retorna las reseñas de ese periodista de partidos con tarjeta roja 
        [HttpPost]
        public IActionResult Estadisticas(string emailPeriodista)
        {
            List<Resenia> listaRes = s.GetReseniaPeriodistas(emailPeriodista);
            Usuario unPeriodista = s.GetUsuarioPorEmail(emailPeriodista);
            if (unPeriodista == null)
            {
                ViewBag.msg = "Periodista inexistente";
            }
            else if (listaRes.Count() == 0)
            {
                ViewBag.msg = "No hay partidos con tarjeta roja reseñados";
            }
            return View(listaRes);
        }

        // IActionResult que envía a la vista de reseñas de un determinado periodista
        public IActionResult FiltroPeriodista(int id) 
        {
            if (HttpContext.Session.GetString("Tipo") == "Operador")
            {
                List<Resenia> listaRes = s.GetReseniasUnPeriodista(id);
                Usuario unUsuario = s.GetUsuario(id);
                ViewBag.Nombre = unUsuario.Nombre;
                return View(listaRes);
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

Obligatorio Web/Views/Partido/Buscar.cshtml
@model IEnumerable<Dominio.Partido>
<!--Vista que permite buscar partidos entre dos fechas-->

<!--Form que permite seleccionar entre dos fechas-->
<h2>Buscador según fecha de partidos finalizados</h2>
<form method="post">
    Fecha 1: <br />
    <input type="date" name="fecha1" /><br />
    Fecha 2: <br />
    <input type="date" name="fecha2" /><br /><br />
    <input type="submit" class="btn btn-primary" value="Buscar" />
</form>
<br />

<!--Tabla que muestra datos de los partidos finalizados encontrados-->
@if (Model != null)
    {
        if (Model.Count() < 1)
        {
            <p><strong>No hay partidos que figuren dentro de las fechas marcadas</strong></p>
        }
        else
        {
        <table class="table">
            <tr>
                <th>Fecha del partido</th>
                <th>Selección 1</th>
                <th>Selección 2</th>
                <th>Goles selección 1</th>
                <th>Goles selección 2</th>
                <th>Tarjetas amarillas selección 1</th>
                <th>Tarjetas amarillas selección 2</th>
                <th>Tarjetas Rojas selección 1</th>
                <th>Tarjetas Rojas selección 2</th>
            </tr>
            @foreach (var partido in Model)
                {
                <tr>
                    <td>@partido.FechaYhoraDelPartido</td>
                    <td>@partido.Seleccion1.UnPais.Nombre</td>
                    <td>@partido.Seleccion2.UnPais.Nombre</td>
                    <td>@partido.StringGetGoles(partido.Seleccion1)</td>
                    <td>@partido.StringGetGoles(partido.Seleccion2)</td>
                    <td>@partido.GetAmarillas(partido.Seleccion1)</td>
                    <td>@partido.GetAmarillas(partido.Seleccion2)</td>
                    <td>@partido.GetRojas(partido.Seleccion1)</td>
                    <td>@partido.GetRojas(partido.Seleccion2)</td>
                </tr>
                }
        </table>
        }
    }
    else
    {
        <p><strong>Para buscar los partidos dentro de las fechas, debe ingresarlas en el formulario</strong></p>
    }
<!--Boton para volver al inicio-->
<div>
    <a asp-action="Index" asp-controller="Home" class="btn btn-primary">Volver</a>
</div>

Obligatorio Web/Views/Partido/Index.cshtml
@using Microsoft.AspNetCore.Http
@model IEnumerable<Dominio.Partido>

<!--Vista que muestra la lista de partidos-->
<!--En la vista se diferencian los que pueden ver el operador y aquellos de los periodistas-->
<h1>Lista de Partidos</h1>
@if (Context.Session.GetString("Tipo") == "Operador" || (Context.Session.GetString("Tipo") == "Periodista" && ViewBag.Contador > 0))
{
    <table class="table">
        <tr>
            <th>Fecha del partido</th>
            <th>Selección 1</th>
            <th>Selección 2</th>
            @if (Context.Session.GetString("Tipo") == "Operador")
            {
                <th>Cerrar Partido</th>

            }
            else
            {
                <th>Realizar reseña</th>
            }
        </tr>
        @if (Context.Session.GetString("Tipo") == "Operador")
        {
            @foreach (var partido in Model)
            {
                <tr>
                    <td>@partido.FechaYhoraDelPartido</td>
                    <td>@partido.Seleccion1.UnPais.Nombre</td>
                    <td>@partido.Seleccion2.UnPais.Nombre</td>
                    <td>
                        @if (partido.Finalizado == false)
                        {
                            if (partido.GetTipo() == "Eliminatoria")
                            {
                                @Html.ActionLink("Cerrar Partido", "Close", "Eliminatoria", new { partidoId = partido.Id })
                            }
                            else
                            {
                                @Html.ActionLink("Cerrar Partido", "Close", "Grupos", new { partidoId = partido.Id })
                            }

                        }
                        else
                        {
                            <span>Partido cerrado</span>
                        }
                    </td>
                </tr>
            }
        }
        else if (Context.Session.GetString("Tipo") == "Periodista")
        {
            @foreach (var partido in Model)
            {
                @if (partido.Finalizado == true)
                {
                    <tr>
                        <td>@partido.FechaYhoraDelPartido</td>
                        <td>@partido.Seleccion1.UnPais.Nombre</td>
                        <td>@partido.Seleccion2.UnPais.Nombre</td>
                        <td>@Html.ActionLink("Realizar reseña", "Create", "Resenia", new { partidoId = partido.Id })</td>
                    </tr>
                }
            }
        }
    </table>
}
else
{
    <p><strong>No hay partidos finalizados</strong></p>
}
<!--Boton para volver al inicio-->
<div>
    <a asp-action="Index" asp-controller="Home" class="btn btn-primary">Volver</a>
</div>