Obligatorio Web/Controllers/PartidoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Dominio;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Obligatorio_Web.Controllers
{
    public class PartidoController : Controller
    {
        Sistema s = Sistema.Instancia();

        // IActionResult que envia a la vista la lista de partidos, asi como un metodo que nos indica si hay partidos finalizados
        public IActionResult Index()
        {
            if (HttpContext.Session.GetInt32("Id") != null)
            {
                ViewBag.Contador = s.PartidosFinalizados();
                return View(s.GetPartidos());
            }
            return RedirectToAction("Index", "Home");
        }

        //IActionResult (get) que envia a la vista del buscador de partidos
        [HttpGet]
        public IActionResult Buscar()
        {
            if (HttpContext.Session.GetString("Tipo") == "Operador")
            {
                return View();
            }
                return RedirectToAction("Index", "Home");
        }

        //IActionResult (post) que devuelve a la vista la lista de partidos finalizados entre dos fechas
        [HttpPost]
        public IActionResult Buscar(DateTime fecha1, DateTime fecha2)
        {
            List<Partido> listaFiltrada = s.GetPartidos(fecha1, fecha2);
            
            return View(listaFiltrada);
        }
    }
}

Obligatorio Web/Controllers/ReseniaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Dominio;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Obligatorio_Web.Controllers
{
    public class ReseniaController : Controller
    {
        Sistema s = Sistema.Instancia();

        // IactionResult que envia a la vista las reseñas de un determinado periodista
        // Verifica que sea periodista, y también si la lista de reseñas esta vacia o no
        public IActionResult Index()
        {
            int? idR = HttpContext.Session.GetInt32("Id");
            Usuario usuarioR = s.GetUsuario(idR);
            if (usuarioR != null)
            {
                if (HttpContext.Session.GetString("Tipo") == "Periodista")
                {
                    ViewBag.User = usuarioR;
                    string rol = HttpContext.Session.GetString("Tipo");
                    ViewBag.ListaVacia = s.ListaVaciaPeriodista((Periodista)usuarioR);
                    if (rol == "Periodista")
                    {
                        return View(s.GetResenias());
                    }
                }
            }
            return RedirectToAction("Index", "Home");
        }

        // IActionResult (get) que envia a la vista para que el peridoista realice una reseña
        [HttpGet]
        public IActionResult Create(int partidoId)
        {
            string rol = HttpContext.Session.GetString("Tipo");
            if (rol == "Periodista")
            {
                Partido partidoRes = s.GetPartido(partidoId);
                ViewBag.ElPartido = partidoRes;
                return View();
            }
                return RedirectToAction("Index", "Home");
        }

        // IActionResult (post) que obtiene los datos de la reseña, la da de alta en el sistema y envia mensaje a la vista
        [HttpPost]
        public IActionResult Create(int partidoId, string unTitulo, string unContenido)
        {
              Partido partidoR = s.GetPartido(partidoId);
              ViewBag.ElPartido = partidoR;
              int? idR = HttpContext.Session.GetInt32("Id");
              Usuario usuarioR = s.GetUsuario(idR);

              Resenia res = new Resenia();

              res.UnPartido = partidoR;
              res.UnPeriodista = usuarioR as Periodista;
              res.Fecha = DateTime.Now;
              res.Titulo = unTitulo;
              res.Contenido = unContenido;

              try
              {
                  s.AltaResenia(res);
                  ViewBag.Msg = "Datos guardados correctamente";
              }
              catch (Exception ex)
              {
                  ViewBag.Msg = ex.Message;
              }

              return View();
        }

        // IActionResult que envia a la vista los detalles de una reseña determinada
        public IActionResult Details(int id)
        {
            string rol = HttpContext.Session.GetString("Tipo");
            if (rol == "Periodista")
            {
                Resenia reseniaR = s.GetResenia(id);
                return View(reseniaR);
            }
                return RedirectToAction("Index", "Home");
        }

        // IActionResult (get) que envía a la vista del buscador de reseñas de partidos con tarjeta roja de un periodista 
        public IActionResult Estadisticas()
        {
            if (HttpContext.Session.GetString("Tipo") == "Operador")
            {
                return View();
            }
            return RedirectToAction("Index", "Home");
        }

        // IActionResult (post) que obtiene el email del periodista y retorna las reseñas de ese periodista de partidos con tarjeta roja 
        [HttpPost]
        public IActionResult Estadisticas(string emailPeriodista)
        {
            List<Resenia> listaRes = s.GetReseniaPeriodistas(emailPeriodista);
            Usuario unPeriodista = s.GetUsuarioPorEmail(emailPeriodista);
            if (unPeriodista == null)
            {
                ViewBag.msg = "Periodista inexistente";
            }
            else if (listaRes.Count() == 0)
            {
                ViewBag.msg = "No hay partidos con tarjeta roja reseñados";
            }
            return View(listaRes);
        }

        // IActionResult que envía a la vista de reseñas de un determinado periodista
        public IActionResult FiltroPeriodista(int id) 
        {
            if (HttpContext.Session.GetString("Tipo") == "Operador")
            {
                List<Resenia> listaRes = s.GetReseniasUnPeriodista(id);
                Usuario unUsuario = s.GetUsuario(id);
                ViewBag.Nombre = unUsuario.Nombre;
                return View(listaRes);
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

Obligatorio Web/Controllers/SeleccionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Dominio;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Obligatorio_Web.Controllers
{
    public class SeleccionController : Controller
    {
        Sistema s = Sistema.Instancia();

        // IActionResult que envia todas las selecciones a la vista
        public IActionResult Index()
        {
            string tipoUsuario = HttpContext.Session.GetString("Tipo");

            if (tipoUsuario != "Periodista")
            {
                return View(s.GetSelecciones());
            }

            return RedirectToAction("Index", "Home");

        }
        
        // IActionResult que envía a la vista la o las selecciones con mas goles
        public IActionResult Estadisticas()
        {
            if (HttpContext.Session.GetString("Tipo") == "Operador")
            {
                List<Seleccion> sel = s.SeleccionConMasGoles();
                return View(sel);
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

Obligatorio Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Obligatorio_Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Obligatorio_Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (Context.Session.GetInt32("Id") == null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Iniciar Sesion</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Periodista" asp-action="Create">Registrarse</a>
                            </li>
                        }
                        @if (Context.Session.GetString("Tipo") == "Operador")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Periodista" asp-action="Index">Periodistas</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Operador" asp-action="Estadisticas">Estadisticas</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Partido" asp-action="Buscar">Buscar partido/s</a>
                            </li>
                        }

                        @if (Context.Session.GetString("Tipo") != "Periodista")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Seleccion" asp-action="Index">Selecciones</a>
                            </li>
                        }
                        @if (Context.Session.GetString("Tipo") == "Periodista")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Resenia" asp-action="Index">Reseñas</a>
                            </li>
                        }
                        @if (Context.Session.GetInt32("Id") != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Partido" asp-action="Index">Partidos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">Cerrar Sesion</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Obligatorio_Web
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>